### ISSUE TITLE
Crash with a runtime error

### ISSUE THREAD

**Issue by LaHaine** [vpenso/prometheus-slurm-exporter#1] opened 2017-08-31 08:13 UTC
I've been testing the prometheus exporter and over night it crashed with this message
````
panic: runtime error: index out of range

goroutine 38867 [running]:
panic(0x8ccec0, 0xc82000a0f0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.SplitColonValueToFloat(0xc8202613c1, 0x11, 0x0)
	/home/test/build/src/github.com/vpenso/prometheus-slurm-exporter/scheduler.go:59 +0xc5
main.ParseSchedulerMetrics(0xc8201d6000, 0x1015, 0x1e00, 0xc8202bec00)
	/home/test/build/src/github.com/vpenso/prometheus-slurm-exporter/scheduler.go:72 +0x1c3
main.SchedulerGetMetrics(0x4307fd)
	/home/test/build/src/github.com/vpenso/prometheus-slurm-exporter/scheduler.go:81 +0x48
main.(*SchedulerCollector).Collect(0xc82005b000, 0xc8201ff380)
	/home/test/build/src/github.com/vpenso/prometheus-slurm-exporter/scheduler.go:117 +0x1c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc8200fc1f0,
0xc8201ff380, 0x7f3fa171eae0, 0xc82005b000)
	/home/test/build/src/github.com/vpenso/prometheus-slurm-exporter/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x58
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/test/build/src/github.com/vpenso/prometheus-slurm-exporter/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x360
````

I am running slurm 16.05.10 on Enterprise Linux 7.3, but the exporter was built using Go 1.6 on Ubuntu.

**Comment by mtds** [comment] 2017-11-21 15:08
The error is generated while extracting the output  from the ``sdiag`` command. One of the metric
related to the scheduler is not in the expected position and the ``SplitColonValueToFloat()`` function
fails while parsing an empty string, thus generating a panic error.

This exporter was tested against Slurm 14.03.9 but since then the output from  ``sdiag`` is slightly
changed. I had stumbled into the same problem (a crash) against Slurm 17.02.7.
The Linux or the Golang compiler version are not relevant to this issue.

A quick fix would be to check for empty strings inside the ``SplitColonValueToFloat()`` function
but it will not solve the problem, since in the case of Slurm 16.x or 17.x it will reports wrong
values for the ``backfilling`` scheduler stats.

We are planning to use this exporter for our cluster, so we'll try to fix the issue for the recent versions 
of Slurm.

**Comment by mtds** [comment] 2017-11-24 15:17
With the pull request #2 (if merged) the exporter will be able to run without crashes.

The problem is related to the fact that the output of the ``sdiag`` command not always
reports all the metrics. For example a newly started Slurm cluster or one which was
never subjected to an heavy workload will never reports a ``Depth Mean`` value for
the backfill stats.

The proposed pull request will alter this behavior by simply checking if the string
extracted from the ``sdiag`` output is empty or not. In the first case the metric will
be automatically set to zero.

**Comment by vpenso** [comment] 2017-11-27 09:13
Thanks for the contribution...this should be fixed now.

**Closed by vpenso** 2017-11-27 09:13 UTC
