### ISSUE TITLE
panic: runtime error: index out of range [4] with length 4

### ISSUE THREAD

**Issue by nicolaven** [vpenso/prometheus-slurm-exporter#56] opened 2021-05-11 16:51 UTC
Hi!

I am seeing the following problem
```
[root@ip-10-3-5-236 prometheus-slurm-exporter]# curl http://localhost:8080/metrics
panic: runtime error: index out of range [4] with length 4

goroutine 66 [running]:
main.ParseNodeMetrics(0xc0006a0000, 0x328ca, 0x3fe00, 0x0)
        /root/prometheus-slurm-exporter/node.go:56 +0x6cf
main.NodeGetMetrics(0x0)
        /root/prometheus-slurm-exporter/node.go:40 +0x2a
main.(*NodeCollector).Collect(0xc0001986c0, 0xc0000a8540)
        /root/prometheus-slurm-exporter/node.go:128 +0x37
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /root/prometheus-slurm-exporter/go/modules/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /root/prometheus-slurm-exporter/go/modules/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe8e
curl: (52) Empty reply from server
[1]+  Exit 2                  /usr/bin/prometheus-slurm-exporter
[root@ip-10-3-5-236 prometheus-slurm-exporter]# 
```

any suggestion ?

**Comment by nicolaven** [comment] 2021-05-13 16:37
Hi,

any sugestion here?

**Comment by mtds** [comment] 2021-05-14 07:53
A couple of questions:

1. Are you using the latest version of this exporter?
2. Which version of Slurm are you running? 18.x? 19.x? 20.x?
3. The error you are seeing is most likely caused by failure in parsing the output of the following command (launched internally by the exporter itself):
```bash
sinfo -h -N -O "NodeList,AllocMem,Memory,CPUsState,StateLong"
```
Can you execute the previous command and report the output back to me? The first 8/10 lines are sufficient.

**Comment by mtds** [comment] 2021-05-25 06:56
* No further info provided, closing for the time being.
* Eventually re-open it when more info are available.

**Closed by mtds** 2021-05-25 06:56 UTC

**Comment by gbeyer3** [comment] 2022-07-11 16:04
Hello, I'm getting the same crash as @nicolaven .  Nicola - were you able to resolve this?  

panic: runtime error: index out of range [4] with length 4

goroutine 26 [running]:
main.ParseNodeMetrics(0xc000140000, 0x25e, 0x600, 0x87080d)
/storage/home/hhiveman1/gbeyer3/prometheus-slurm-exporter/node.go:56 +0x6d6
main.NodeGetMetrics(0x1)
/storage/home/hhiveman1/gbeyer3/prometheus-slurm-exporter/node.go:40 +0x2a
main.(*NodeCollector).Collect(0xc000020030, 0xc000072660)
/storage/home/hhiveman1/gbeyer3/prometheus-slurm-exporter/node.go:128 +0x37
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
/storage/home/hhiveman1/gbeyer3/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x12b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
/storage/home/hhiveman1/gbeyer3/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe4d

Answering the questions you asked Nicola:

I am using the latest version of the slurm-exporter which I cloned directly from your repo and built using instructions in DEVELOPMENT.md ver 0.20

slurm version 22.05.0

sinfo -h -N -O "NodeList,AllocMem,Memory,CPUsState,StateLong"
atl1-1-02-018-35 0 515741 0/64/0/64 idle
atl1-1-03-002-35 0 191856 0/24/0/24 idle
compile-coda 0 191881 0/24/0/24 idle
compute-dev-slurm-1-0 3770 0/4/0/4 idle
compute-dev-slurm-1-0 3770 0/4/0/4 idle
compute-dev-slurm-2-0 3770 0/4/0/4 idle
